### ISSUE TITLE
`CommandChecker` seems to fail on indexes using expressions rather than columns

### ISSUE THREAD

**Issue by gstokkink** [fatkodima/online_migrations#30]
Hi,

We have some indexes on a table that were created using expressions, for instance:

```
class AddLocaleDomainIndex < ActiveRecord::Migration[5.2]
  def change
    add_index :organizations, 'avals(locale_domain)', using: :gin, name: 'index_organizations_on_locale_domain'
  end
end
```

Now, when we try to remove a column from this table without using `safety_assured`, the `CommandChecker` crashes as follows:

```
undefined method `&' for "avals(locale_domain)":String
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/command_checker.rb:389:in `block in check_columns_removal'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/command_checker.rb:388:in `select'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/command_checker.rb:388:in `check_columns_removal'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/command_checker.rb:116:in `do_check'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/command_checker.rb:34:in `check'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/online_migrations-0.7.2/lib/online_migrations/migration.rb:21:in `method_missing'
/Users/bookingexperts/Code/monorepo/apps/parkcms/db/migrate/20230530085532_remove_module_multi_booking_column_from_organizations.rb:3:in `up'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `public_send'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `exec_migration'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/Users/bookingexperts/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
```

Seems like the `CommandChecker` uses `column.indexes`, which can also contain expressions as strings, for PostgreSQL at least:

https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L118

Thanks in advance for looking into this!

**Comment by fatkodima** [comment]
@gstokkink Thanks for the report! Can you verify the merged fix fixes your issue?

**Comment by gstokkink** [comment]
@fatkodima that works, thanks 👍

**Comment by fatkodima** [comment]
Released a new version with this change.
